
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/retrofit
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: org.bristolenergynetwork.retrofit.model
  mapper-locations: classpath*:mapper/*Mapper.xml